export default function SampleStoryCard({ title, text, readingTime, genre }) {
  return (
    <div className="sample-story-card">
      <h3>{title}</h3>
      <p className="sample-story-meta">
        {readingTime && `${readingTime} min read`}
        {readingTime && genre && ' · '}
        {genre && `Generated by Playla AI`}
      </p>
      <div className="sample-story-text">{text}</div>
    </div>
  )
}
